name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}
    
    steps:
      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            bash
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          cmake -B build

      - name: Build
        run: |
          cmake --build build

      - name: Unit Test
        run: |
          ctest --test-dir build

      - name: Install
        run: |
          cmake --install build --prefix install
      
      - name: Upload
        uses: actions/upload-artifact@4
        with:
          name: pe-tools
          path: install/bin
